# Generated by Django 5.1.1 on 2024-10-25 18:16
from datetime import datetime

from django.db import migrations, models


class SeperateDatabaseAndStateIfFeatureUnavailable(migrations.SeparateDatabaseAndState):
    def __init__(self, feature, unavailable_operations, state_operations):
        super().__init__([], state_operations)
        self.feature = feature
        self.unavailable_operations = unavailable_operations

    def deconstruct(self):
        _, _ , kwargs = super().deconstruct()
        kwargs = {}
        kwargs["feature"] = self.feature
        kwargs["unavailable_operations"] = self.unavailable_operations
        return (self.__class__.__qualname__, [], kwargs)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if not getattr(schema_editor.connection.features, self.feature):
            self.database_operations = self.unavailable_operations
        return super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if not getattr(schema_editor.connection.features, self.feature):
            self.database_operations = self.unavailable_operations
        return super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0009_remove_results_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbtaskresult",
            name="queue_name",
            field=models.CharField(
                default="default", max_length=64, verbose_name="queue name"
            ),
        ),
        migrations.AddIndex(
            model_name="dbtaskresult",
            index=models.Index(fields=["status"], name="django_task_status_9e2de0_idx"),
        ),
        migrations.AddIndex(
            model_name="dbtaskresult",
            index=models.Index(
                fields=["queue_name"], name="django_task_queue_n_99c321_idx"
            ),
        ),
        migrations.AlterModelOptions(
            name='dbtaskresult',
            options={'ordering': [models.OrderBy(models.F('priority'), descending=True), models.OrderBy(models.F('run_after'), nulls_last=True)], 'verbose_name': 'Task Result', 'verbose_name_plural': 'Task Results'},
        ),
        SeperateDatabaseAndStateIfFeatureUnavailable(
            feature="supports_order_by_nulls_modifier",
            unavailable_operations=[
                # if the database does not support NULLS_LAST in order by, use an alternative migration
                # that treats a null run_after as a max datetime, for ordering purposes.
                migrations.AddIndex(
                    model_name="dbtaskresult",
                    index=models.Index(
                        models.OrderBy(models.F("priority"), descending=True),
                        models.OrderBy(
                            models.functions.Coalesce(models.F("run_after"), datetime(9999,12,31)),
                            descending=False
                        ),
                        name="django_task_ordering_idx",
                    ),
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="dbtaskresult",
                    index=models.Index(
                        models.OrderBy(models.F("priority"), descending=True),
                        models.OrderBy(models.F("run_after"), descending=False, nulls_last=True),
                        name="django_task_ordering_idx",
                    ),
                ),
            ]
        ),
    ]
